apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: feeds-dispatcher
  namespace: argocd
spec:
  description: ACP-ACRS Feeds Dispatcher

  sourceRepos:
    - "{account}.dkr.ecr.eu-west-1.amazonaws.com/feeds-dispatcher/*"

  destinations:
    - namespace: feeds-dispatcher-dev
      server: https://kubernetes.default.svc
    - namespace: feeds-dispatcher-oat
      server: https://kubernetes.default.svc
    - namespace: feeds-dispatcher-prod
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: "apps"
      kind: Deployment
    - group: ""
      kind: Service
    - group: ""
      kind: ConfigMap
    - group: "autoscaling"
      kind: HorizontalPodAutoscaler
